/*
 * Thermal-FIST package
 *
 * Copyright (c) 2024-2026 Volodymyr Vovchenko
 *
 * GNU General Public License (GPLv3 or later)
 */
#ifndef PHASESHIFTCHANNEL_H
#define PHASESHIFTCHANNEL_H

/**
 * \file PhaseShiftChannel.h
 *
 * \brief Physical description of an S-matrix two-body scattering channel (an
 *        isospin multiplet) plus the helpers that turn it into a Thermal-FIST
 *        list module: a particle table (list-<name>.dat), a decays file
 *        (decays-<name>.dat) and the routine that attaches a (selectable)
 *        PhaseShiftModel's delta(M) to each cluster member after loading.
 *
 * The channel is model-independent: it fixes the constituents, quantum numbers
 * and the decay (isospin-Clebsch-Gordan) structure. The dynamics, delta(M),
 * come from a separate PhaseShiftModel so the same channel can be evaluated
 * with different parametrizations or a tabulated phase shift.
 */

#include <string>
#include <vector>
#include <map>
#include <utility>

#include "HRGPhaseShifts/PhaseShiftModel.h"

namespace thermalfist {

  class ThermalParticleSystem; // forward declaration

  namespace PhaseShifts {

    /**
     * \brief Flavour-family digit of the synthetic PDG id (see PhaseShiftPdgId).
     */
    enum ChannelFamily {
      FamilyPiPi  = 1, ///< pi pi
      FamilyPiK   = 2, ///< pi K
      FamilyKK    = 3, ///< K Kbar
      FamilyPiN   = 4, ///< pi N
      FamilyPiEta = 5  ///< pi eta
    };

    /**
     * \brief One scattering constituent: its isospin and the PDG codes of its
     *        charge (Iz) states, used to build the isospin-CG decay channels.
     */
    struct PhaseShiftConstituent {
      int twoIsospin;                          ///< 2 * isospin of the constituent
      std::map<int, long long> chargeStates;   ///< 2*Iz -> PDG code of that charge state
    };

    /**
     * \brief Physical (model-independent) definition of a scattering channel.
     *
     * The electric charge of each member follows from Q = Iz + (B + S + C)/2.
     */
    struct PhaseShiftChannel {
      std::string name;                ///< label, e.g. "pipi_I2"
      int    family;                   ///< ChannelFamily flavour digit
      double m1, m2;                   ///< constituent masses [GeV]
      double Mmax;                     ///< integration cutoff [GeV]
      int    statistics;               ///< cluster stat (-1 Bose, +1 Fermi, 0 Boltzmann)
      int    twoI;                     ///< 2 * total isospin
      int    B, S, C;                  ///< cluster baryon / strangeness / charm
      PhaseShiftConstituent a, b;      ///< the two scattering constituents (for decays)
      std::vector<long long> subsumedPdg; ///< PDG codes of resonances this channel replaces
      int    quadratureNodes;          ///< Gauss-Legendre nodes for the q-integral

      PhaseShiftChannel()
        : family(FamilyPiPi), m1(0.), m2(0.), Mmax(0.), statistics(-1),
          twoI(0), B(0), S(0), C(0), quadratureNodes(64) {}
    };

    /**
     * \brief Synthetic PDG id (magnitude) of one partial wave of a channel member,
     *        following the spirit of the PDG MC numbering.
     *
     * Layout (8 digits): "9 9 F (2I) (2|Iz|) n n (2J+1)". The LAST digit is the
     * wave's spin degeneracy 2J+1 (as in PDG); electric charge, baryon number and
     * strangeness are carried by the ThermalParticle fields, not packed into the
     * code; the 8-digit 99-prefix stays clear of all real PDG codes. The
     * antiparticle uses the negative.
     *
     * \param ch          Channel (provides family and twoI).
     * \param twoIz        2*Iz of the member (magnitude uses |2Iz|).
     * \param twoJplus1    2J+1 of the wave (1..9); becomes the last digit.
     */
    long long PhaseShiftPdgId(const PhaseShiftChannel& ch, int twoIz, int twoJplus1);

    /**
     * \brief Isospin-Clebsch-Gordan decay channels of the (I, Iz) member into its
     *        constituent charge states. Independent of the partial wave.
     *
     * \return List of (branching ratio, {daughter PDG, daughter PDG}). For
     *         identical constituents the two orderings are merged; the branchings
     *         sum to 1.
     */
    std::vector<std::pair<double, std::pair<long long, long long> > >
      ChannelDecays(const PhaseShiftChannel& ch, int twoIz);

    /**
     * \brief Write the particle table (list-<name>.dat) for the channel/model.
     *
     * One row per (Iz >= 0, partial wave) member, marked unstable; antiparticles
     * are generated by Thermal-FIST at load time.
     */
    void WritePhaseShiftListFile(const PhaseShiftChannel& ch, const PhaseShiftModel& model,
                                 const std::string& listFile);

    /**
     * \brief Write the decays file (decays-<name>.dat) for the channel/model.
     *
     * Each (Iz >= 0, partial wave) member gets the isospin-CG decay channels into
     * its constituents; antiparticle decays are generated by Thermal-FIST.
     */
    void WritePhaseShiftDecaysFile(const PhaseShiftChannel& ch, const PhaseShiftModel& model,
                                   const std::string& decaysFile);

    /**
     * \brief Convenience: write both files into \p dir as list-<name>.dat and
     *        decays-<name>.dat.
     */
    void WritePhaseShiftFiles(const PhaseShiftChannel& ch, const PhaseShiftModel& model,
                              const std::string& dir);

    /**
     * \brief After a list build, attach a single-wave PhaseShiftDensity (from the
     *        chosen model) to every cluster member of the channel present in the
     *        system, particles and antiparticles alike.
     *
     * The model's waves are matched to members by 2J+1. Call this after LoadList()
     * (and before model calculations).
     *
     * \return The PDG ids that received a density (signed).
     */
    std::vector<long long> AttachDensities(ThermalParticleSystem& TPS,
                                           const PhaseShiftChannel& ch,
                                           const PhaseShiftModel& model);

    /**
     * \brief Graceful resonance subsumption: remove ch.subsumedPdg (both charge
     *        signs) from the system if present, to avoid double counting. A
     *        no-op for codes not in the list. Returns the codes actually removed.
     */
    std::vector<long long> SubsumeResonances(ThermalParticleSystem& TPS,
                                             const PhaseShiftChannel& ch);

    /// Catalog: the repulsive pi-pi I=2 channel (constituents + structure only).
    PhaseShiftChannel PiPi_I2_Channel();

    // ------------------------------------------------------------------------
    // High-level convenience API (no file juggling).
    // ------------------------------------------------------------------------

    /**
     * \brief One-call: add a fully-wired phase-shift channel to an already-loaded
     *        ThermalParticleSystem.
     *
     * Adds the cluster members and their antiparticles, sets the isospin-CG decay
     * channels (charge-conjugated for antiparticles), attaches the chosen model's
     * delta(M) density to each member, removes any subsumed resonances, and
     * reprocesses the decays so feeddown includes the new clusters. The channel's
     * constituent species (e.g. the pions) must already be present in the list.
     *
     * Typical use:
     * \code
     *   ThermalParticleSystem TPS("input/list/PDG2020/list.dat");
     *   PhaseShifts::AddPhaseShiftChannel(TPS, PhaseShifts::PiPi_I2_Channel(),
     *       PhaseShifts::AnalyticModel("pipi_I2:GarciaMartin2011"));
     *   ThermalModelIdeal model(&TPS);
     * \endcode
     *
     * \return The PDG ids of the members added (signed).
     */
    std::vector<long long> AddPhaseShiftChannel(ThermalParticleSystem& TPS,
                                                const PhaseShiftChannel& ch,
                                                const PhaseShiftModel& model);

    /// Look up a catalog channel by name (e.g. "pipi_I2").
    /// \throws std::invalid_argument for an unknown name.
    PhaseShiftChannel ChannelByName(const std::string& name);

    /// Parse a model spec into a PhaseShiftModel:
    ///   "tab:<2J+1>=<file>[,<2J+1>=<file>...]" -> TabulatedModel,
    ///   anything else                          -> AnalyticModel(spec).
    PhaseShiftModel ParsePhaseShiftModel(const std::string& spec);

    /**
     * \brief One-call: add every channel listed in a single config file.
     *
     * The file lists one channel per line as "<channel_name>  <model_spec>"
     * ('#' comments and blank lines ignored), e.g.
     * \verbatim
     *   # channel   model
     *   pipi_I2     pipi_I2:GarciaMartin2011
     *   # tabulated alternative:
     *   # pipi_I2   tab:1=delta_S.dat,5=delta_D.dat
     * \endverbatim
     * Each line is resolved via ChannelByName() + ParsePhaseShiftModel() and
     * added with AddPhaseShiftChannel().
     *
     * \return The PDG ids of all members added across all channels.
     */
    std::vector<long long> AddPhaseShiftChannelsFromFile(ThermalParticleSystem& TPS,
                                                         const std::string& configFile);

  } // namespace PhaseShifts

} // namespace thermalfist

#endif
